/**
 * Vehicle Constants Module
 * Centralized constants for vehicle-related dropdowns and validations
 */

// Vehicle Colors
export const VEHICLE_COLORS = [
  'White',
  'Black',
  'Silver',
  'Gray',
  'Red',
  'Blue',
  'Green',
  'Brown',
  'Beige',
  'Gold',
  'Orange',
  'Yellow',
  'Purple',
  'Pink',
  'Maroon',
  'Navy',
  'Turquoise',
  'Tan',
  'Cream',
  'Burgundy',
] as const;

export type VehicleColor = typeof VEHICLE_COLORS[number];

// Vehicle Makes/Brands
export const VEHICLE_MAKES = [
  'Toyota',
  'Honda',
  'Ford',
  'Chevrolet',
  'Nissan',
  'BMW',
  'Mercedes-Benz',
  'Audi',
  'Volkswagen',
  'Hyundai',
  'Kia',
  'Mazda',
  'Subaru',
  'Jeep',
  'Dodge',
  'Ram',
  'GMC',
  'Cadillac',
  'Lexus',
  'Acura',
  'Infiniti',
  'Lincoln',
  'Buick',
  'Chrysler',
  'Volvo',
  'Porsche',
  'Tesla',
  'Land Rover',
  'Jaguar',
  'Mini',
  'Mitsubishi',
  'Genesis',
  'Alfa Romeo',
  'Fiat',
  'Maserati',
  'Bentley',
  'Rolls-Royce',
  'Ferrari',
  'Lamborghini',
  'McLaren',
  'Aston Martin',
  'Suzuki',
  'Isuzu',
  'Other',
] as const;

export type VehicleMake = typeof VEHICLE_MAKES[number];

// Vehicle Models - Linked to Makes
export const VEHICLE_MODELS: Record<VehicleMake, readonly string[]> = {
  Toyota: [
    'Camry',
    'Corolla',
    'RAV4',
    'Highlander',
    'Prius',
    'Sienna',
    'Tacoma',
    'Tundra',
    '4Runner',
    'Sequoia',
    'Land Cruiser',
    'Avalon',
    'Venza',
    'C-HR',
    'Yaris',
    'GR86',
    'Supra',
  ],
  Honda: [
    'Accord',
    'Civic',
    'CR-V',
    'Pilot',
    'Odyssey',
    'Ridgeline',
    'Passport',
    'HR-V',
    'Fit',
    'Insight',
    'Clarity',
  ],
  Ford: [
    'F-150',
    'F-250',
    'F-350',
    'Mustang',
    'Explorer',
    'Escape',
    'Edge',
    'Expedition',
    'Ranger',
    'Bronco',
    'Bronco Sport',
    'Mach-E',
    'Transit',
    'EcoSport',
  ],
  Chevrolet: [
    'Silverado',
    'Equinox',
    'Tahoe',
    'Suburban',
    'Traverse',
    'Malibu',
    'Impala',
    'Camaro',
    'Corvette',
    'Trax',
    'Blazer',
    'Colorado',
    'Bolt',
  ],
  Nissan: [
    'Altima',
    'Sentra',
    'Rogue',
    'Pathfinder',
    'Armada',
    'Frontier',
    'Titan',
    'Murano',
    'Maxima',
    'Leaf',
    'Kicks',
    'Versa',
  ],
  BMW: [
    '3 Series',
    '5 Series',
    '7 Series',
    'X1',
    'X3',
    'X5',
    'X7',
    'X2',
    'X4',
    'X6',
    'Z4',
    'i4',
    'iX',
    'M3',
    'M5',
  ],
  'Mercedes-Benz': [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLC',
    'GLE',
    'GLS',
    'A-Class',
    'CLA',
    'GLA',
    'GLB',
    'G-Class',
    'AMG GT',
    'EQC',
    'EQS',
  ],
  Audi: [
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'e-tron',
    'TT',
    'R8',
  ],
  Volkswagen: [
    'Jetta',
    'Passat',
    'Atlas',
    'Tiguan',
    'Arteon',
    'Golf',
    'ID.4',
    'Taos',
    'Touareg',
  ],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Kona',
    'Venue',
    'Ioniq',
    'Nexo',
  ],
  Kia: [
    'Forte',
    'Optima',
    'Sorento',
    'Sportage',
    'Telluride',
    'Rio',
    'Stinger',
    'Soul',
    'EV6',
    'Niro',
  ],
  Mazda: [
    'Mazda3',
    'Mazda6',
    'CX-3',
    'CX-5',
    'CX-9',
    'CX-30',
    'CX-50',
    'MX-5 Miata',
  ],
  Subaru: [
    'Outback',
    'Forester',
    'Crosstrek',
    'Ascent',
    'Impreza',
    'Legacy',
    'WRX',
    'BRZ',
  ],
  Jeep: [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Gladiator',
    'Wagoneer',
    'Grand Wagoneer',
  ],
  Dodge: [
    'Challenger',
    'Charger',
    'Durango',
    'Journey',
    'Grand Caravan',
  ],
  Ram: [
    '1500',
    '2500',
    '3500',
    'ProMaster',
    'ProMaster City',
  ],
  GMC: [
    'Sierra',
    'Yukon',
    'Yukon XL',
    'Acadia',
    'Terrain',
    'Canyon',
  ],
  Cadillac: [
    'Escalade',
    'XT4',
    'XT5',
    'XT6',
    'CT4',
    'CT5',
    'CT6',
    'Lyriq',
  ],
  Lexus: [
    'ES',
    'IS',
    'GS',
    'LS',
    'NX',
    'RX',
    'GX',
    'LX',
    'UX',
    'RC',
    'LC',
  ],
  Acura: [
    'ILX',
    'TLX',
    'RLX',
    'RDX',
    'MDX',
    'NSX',
  ],
  Infiniti: [
    'Q50',
    'Q60',
    'Q70',
    'QX50',
    'QX55',
    'QX60',
    'QX80',
  ],
  Lincoln: [
    'Corsair',
    'Nautilus',
    'Aviator',
    'Navigator',
  ],
  Buick: [
    'Encore',
    'Envision',
    'Enclave',
  ],
  Chrysler: [
    '300',
    'Pacifica',
    'Voyager',
  ],
  Volvo: [
    'S60',
    'S90',
    'V60',
    'V90',
    'XC40',
    'XC60',
    'XC90',
  ],
  Porsche: [
    '911',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
    'Boxster',
    'Cayman',
  ],
  Tesla: [
    'Model S',
    'Model 3',
    'Model X',
    'Model Y',
    'Cybertruck',
  ],
  'Land Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
    'Discovery',
    'Discovery Sport',
    'Defender',
  ],
  Jaguar: [
    'XE',
    'XF',
    'F-Pace',
    'E-Pace',
    'I-Pace',
    'F-Type',
  ],
  Mini: [
    'Cooper',
    'Countryman',
    'Clubman',
    'Paceman',
  ],
  Mitsubishi: [
    'Outlander',
    'Eclipse Cross',
    'Mirage',
    'Outlander Sport',
  ],
  Genesis: [
    'G70',
    'G80',
    'G90',
    'GV70',
    'GV80',
  ],
  'Alfa Romeo': [
    'Giulia',
    'Stelvio',
    '4C',
  ],
  Fiat: [
    '500',
    '500X',
    '500L',
    '124 Spider',
  ],
  Maserati: [
    'Ghibli',
    'Quattroporte',
    'Levante',
    'MC20',
  ],
  Bentley: [
    'Continental',
    'Bentayga',
    'Flying Spur',
  ],
  'Rolls-Royce': [
    'Ghost',
    'Wraith',
    'Dawn',
    'Cullinan',
    'Phantom',
  ],
  Ferrari: [
    '488',
    'F8',
    'SF90',
    'Roma',
    'Portofino',
    'GTC4Lusso',
  ],
  Lamborghini: [
    'Huracán',
    'Aventador',
    'Urus',
  ],
  McLaren: [
    '570S',
    '720S',
    'GT',
    'Artura',
  ],
  'Aston Martin': [
    'DB11',
    'Vantage',
    'DBS',
    'DBX',
  ],
  Suzuki: [
    'Swift',
    'SX4',
    'Grand Vitara',
    'Kizashi',
  ],
  Isuzu: [
    'D-Max',
    'MU-X',
  ],
  Other: ['Other'],
} as const;

// Transmission Types
export const TRANSMISSION_TYPES = [
  'Manual',
  'Automatic',
  'CVT',
  'Dual-Clutch',
  'Semi-Automatic',
] as const;

export type TransmissionType = typeof TRANSMISSION_TYPES[number];

// Transmission Type Mapping (Display Name -> Enum Value)
export const TRANSMISSION_ENUM_MAP: Record<TransmissionType, string> = {
  'Manual': 'MANUAL',
  'Automatic': 'AUTOMATIC',
  'CVT': 'CVT',
  'Dual-Clutch': 'DUAL_CLUTCH',
  'Semi-Automatic': 'SEMI_AUTOMATIC',
} as const;

// Transmission Enum to Display Name Mapping (Enum Value -> Display Name)
export const TRANSMISSION_DISPLAY_MAP: Record<string, TransmissionType> = {
  'MANUAL': 'Manual',
  'AUTOMATIC': 'Automatic',
  'CVT': 'CVT',
  'DUAL_CLUTCH': 'Dual-Clutch',
  'SEMI_AUTOMATIC': 'Semi-Automatic',
} as const;

// Fuel Types (for consistency, matching existing enum)
export const FUEL_TYPES = [
  'Gasoline',
  'Diesel',
  'Electric',
  'Hybrid',
] as const;

export type FuelType = typeof FUEL_TYPES[number];

// Fuel Type Mapping (Display Name -> Enum Value)
export const FUEL_TYPE_ENUM_MAP: Record<FuelType, string> = {
  'Gasoline': 'GASOLINE',
  'Diesel': 'DIESEL',
  'Electric': 'ELECTRIC',
  'Hybrid': 'HYBRID',
} as const;

// Helper function to get models for a specific make
export function getModelsForMake(make: VehicleMake): readonly string[] {
  return VEHICLE_MODELS[make] || [];
}

// Helper function to check if a model belongs to a make
export function isModelValidForMake(make: VehicleMake, model: string): boolean {
  const models = getModelsForMake(make);
  return models.includes(model as any);
}
